# Generated by Django 4.2.7 on 2025-10-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusPass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buspassapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('PAID', 'Fee Paid'), ('ALLOCATED', 'Seat Allocated'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by User')], default='PENDING', max_length=20),
        ),
    ]
