# Generated by Django 4.2.7 on 2025-10-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusPass', '0003_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty')], default='STUDENT', max_length=20),
        ),
    ]
