# Generated by Django 4.2.7 on 2025-10-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusPass', '0004_userprofile_department_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
