# Generated by Django 4.2.7 on 2025-10-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusPass', '0005_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_boarding_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='BoardingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_locations', to='BusPass.busroute')),
            ],
            options={
                'unique_together': {('route', 'name')},
            },
        ),
    ]
