# Generated by Django 4.2.7 on 2025-10-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusPass', '0006_userprofile_preferred_boarding_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinglocation',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='buspassapplication',
            name='paid_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
