# Generated by Django 4.2.7 on 2025-11-02 05:07

import BusPass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusPass', '0007_boardinglocation_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=BusPass.models.user_profile_photo_path, verbose_name='Profile Photo'),
        ),
    ]
